run:
  mode: "skating"          # walking | skating | pronk | backflip | static
  robot: "go2w"
  init_position: "home"   # home | handstand
  sim_freq: 200
  plot: false
  record: True
  record_cycles: 2

motion:
  base_velocity: 1.0
  yaw_rate: 0.0

gait:
  name: "walking"
  freq: 1.5

  params:
    step_length: 0.4
    step_height: 0.15
    duty_ratio: 0.75

skating:            # Skill-specific block
  style: "back_alt"
  push_ratio: 0.2
  recovery_ratio: 0.2
  glide_ratio: 0.6
